create table preferences (id bigint identity not null, user_id bigint not null, preferences TEXT not null, primary key (id));
create table users (id bigint identity not null, password_hash varchar(255) not null, username varchar(255) not null, primary key (id));
alter table preferences add constraint UK52m0vje6w9npud8cqoi2woprs unique (user_id);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table preferences add constraint FKme1hmam0h8w07410h7qkjna5m foreign key (user_id) references users;
create table preferences (id bigint identity not null, user_id bigint not null, preferences TEXT not null, primary key (id));
create table users (id bigint identity not null, password_hash varchar(255) not null, username varchar(255) not null, primary key (id));
alter table preferences add constraint UK52m0vje6w9npud8cqoi2woprs unique (user_id);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table preferences add constraint FKme1hmam0h8w07410h7qkjna5m foreign key (user_id) references users;
create table preferences (id bigint identity not null, user_id bigint not null, preferences TEXT not null, primary key (id));
create table users (id bigint identity not null, password_hash varchar(255) not null, username varchar(255) not null, primary key (id));
alter table preferences add constraint UK52m0vje6w9npud8cqoi2woprs unique (user_id);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table preferences add constraint FKme1hmam0h8w07410h7qkjna5m foreign key (user_id) references users;
create table preferences (id bigint identity not null, user_id bigint not null, preferences TEXT not null, primary key (id));
create table users (id bigint identity not null, password_hash varchar(255) not null, username varchar(255) not null, primary key (id));
alter table preferences add constraint UK52m0vje6w9npud8cqoi2woprs unique (user_id);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table preferences add constraint FKme1hmam0h8w07410h7qkjna5m foreign key (user_id) references users;
